---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "csi-sc-og"
  resources:
    requests:
      storage: 1Gi
